### ISSUE TITLE
Task 10

### ISSUE THREAD

**Issue by VitaliiHurin** [v3il/ma-nodejs-2020#1]
Метод `fetchInTimeOrFail(key, timeout)` реалізовано не правильно. Ми мали на увазі, що якщо діставання за ключем відбувається довше ніж вказане значення `timeout`, то promise має бути зареджекшено.

**Comment by v3il** [comment]
https://github.com/v3il/ma-nodejs-2020/blob/cd3974572fe6516313c0560d3e7aa7299ebf694e/js-check/10.js#L38
